// Auto-generated by ref_generate.py — DO NOT EDIT.
// Butterworth lowpass, order 8, cutoff 0.2 x Nyquist.
// Sections are normalized to b0 == 1; FILTER_GAIN is the removed
// cascade gain and must be pre-applied to the input signal.
#pragma once

#define FILTER_N_SECTIONS 4
static const double FILTER_GAIN = 2.395964410377619e-05;
static const double INPUT_FS    = 1000.0;
static const double INPUT_FREQ  = 120.0;

static const float FILTER_SOS[4][6] = {
    {1.000000000e+00f, 2.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f, -1.026351452e+00f, 2.686401904e-01f},
    {1.000000000e+00f, 2.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f, -1.086858511e+00f, 3.434309363e-01f},
    {1.000000000e+00f, 2.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f, -1.219725370e+00f, 5.076634884e-01f},
    {1.000000000e+00f, 2.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f, -1.451579571e+00f, 7.942510247e-01f}
};

// Direct-form realization of the SAME transfer function (PLR lane).
// b0-normalized (implicit b0 == 1, gain removed = FILTER_GAIN);
// A uses the recurrence sign convention y[n] += A[j] * y[n-j-1].
#define PLR_FILTER_ORDER 8
static const double PLR_FILTER_B[8] = {
    8.0,
    28.0,
    56.0,
    70.0,
    56.0,
    28.0,
    8.0,
    1.0
};
static const double PLR_FILTER_A[8] = {
    4.784514894995809,
    -10.445041065534664,
    13.457719890241552,
    -11.129331039163972,
    6.025260397297648,
    -2.0792738030118763,
    0.417217156989782,
    -0.037200100704845224
};
