// test_performance.cu — throughput measurement for a chosen kernel.
//
// Selects the kernel via one of these compile flags (from run_performance.sh):
//   -DKERNEL_PH     use PH kernels     (ph_kernels.cuh)
//   -DKERNEL_STCR   use STCR kernels   (stcr_kernels.cuh) [future]
//   -DKERNEL_DTCR   use DTCR kernels   (dtcr_kernels.cuh) [future]
//   -DKERNEL_PLR    use PLR kernels    (plr_kernels.cuh)  [future]
//
// Also requires:
//   -DN_SAMPLES_LOG2, -DN_SECTIONS, -DBLOCK_SIZE, -DN_BLOCKS
//
// After the measurement loop, still verifies output against reference.bin.

#include "iir_utils.hpp"
#include "filter_taps.hpp"
#include "gpu_specs.hpp"
#include "measure.cuh"


// ==========================================================================
// Configuration — BLOCK_SIZE, N_BLOCKS, N_SAMPLES_LOG2, N_SECTIONS are
// provided via nvcc -D flags from run.sh.
// N_TB_PER_SM is computed here at compile time via gpu_specs.
// ==========================================================================
#ifndef N_SAMPLES_LOG2
    #error "N_SAMPLES_LOG2 must be defined via -DN_SAMPLES_LOG2=..."
#endif
#ifndef N_SECTIONS
    #error "N_SECTIONS must be defined via -DN_SECTIONS=..."
#endif
#ifndef BLOCK_SIZE
    #error "BLOCK_SIZE must be defined via -DBLOCK_SIZE=..."
#endif
#ifndef N_BLOCKS
    #error "N_BLOCKS must be defined via -DN_BLOCKS=..."
#endif


#define N_SAMPLES        (1 << N_SAMPLES_LOG2)
#define N_THREAD_BLOCKS  (N_SAMPLES / (N_BLOCKS * BLOCK_SIZE))
#define BLOCK_SIZE_LOG2  __builtin_ctz(BLOCK_SIZE)

static_assert(gpu_specs::config_is_valid(BLOCK_SIZE, N_BLOCKS),
              "Invalid (BLOCK_SIZE, N_BLOCKS) for this GPU");

// __launch_bounds__ target: SUPPLY side only (batch-independent), so every
// batch size compiles to an identical binary for a given (BLOCK_SIZE,
// N_BLOCKS) and register allocation cannot vary along the batch axis.
constexpr int N_TB_PER_SM = gpu_specs::compute_supply_tb_per_sm(BLOCK_SIZE, N_BLOCKS);

// Effective residency = min(supply, batch-driven demand). Printed for
// information only; it no longer influences code generation.
constexpr int N_TB_EFFECTIVE = gpu_specs::compute_n_tb_per_sm(BLOCK_SIZE, N_BLOCKS, N_SAMPLES);


// ==========================================================================
// Kernel selection
// ==========================================================================
#if defined(KERNEL_PH)
    #include "ph_kernels.cuh"
#elif defined(KERNEL_STCR)
    #include "stcr_kernels.cuh"
#elif defined(KERNEL_DTCR)
    #include "dtcr_kernels.cuh"
#elif defined(KERNEL_PLR)
    #include "plr_kernels.cuh"
#else
    #error "Select kernel via -DKERNEL_PH (or STCR / DTCR / PLR)"
#endif

// Defaults for kernel families that use the driver-computed launch geometry
// (PH / STCR / DTCR). PLR overrides all three in plr_kernels.cuh: its grid is
// one thread block per PLR chunk, independent of BLOCK_SIZE / N_BLOCKS.
#ifndef KERNEL_GRID_DIM
#define KERNEL_GRID_DIM N_THREAD_BLOCKS
#endif
#ifndef KERNEL_NUM_CHUNKS
#define KERNEL_NUM_CHUNKS ((N_SAMPLES + (BLOCK_SIZE * N_BLOCKS) - 1) / (BLOCK_SIZE * N_BLOCKS))
#endif


#include <iostream>
#include <cassert>
#include <cstdio>
#include <cmath>


int main() {

    std::cout << "=== Performance test ===" << std::endl;
    std::cout << "  GPU profile  = " << gpu_specs::GPU_NAME << std::endl;
    std::cout << "  BLOCK_SIZE   = " << BLOCK_SIZE << std::endl;
    std::cout << "  N_BLOCKS     = " << N_BLOCKS << std::endl;
    std::cout << "  N_TB_PER_SM  = " << N_TB_PER_SM
              << " (launch_bounds, supply side)" << std::endl;
    std::cout << "  N_TB_EFFECT. = " << N_TB_EFFECTIVE
              << " (min of supply and batch demand)" << std::endl;
    std::cout << "  N_SECTIONS   = " << N_SECTIONS << std::endl;
    std::cout << "  N_SAMPLES    = " << N_SAMPLES << std::endl;
#ifdef PLR_KERNELS_CUH
    std::cout << "  PLR geometry : BLOCK=" << PLR_BLOCK_SIZE
              << "  X(eff)=" << PLR_X << "  X_MAX=" << PLR_X_MAX
              << "  N_TB=" << PLR_N_TB
              << "  TB/SM=" << PLR_N_TB_PER_SM << std::endl;
#endif

    // ----- Filter coefficients (generated by ref_generate.py) -----
    // Butterworth lowpass, order 2*N_SECTIONS, cutoff 0.2 x Nyquist, designed
    // directly in SOS form. Sections are normalized to b0 == 1; the removed
    // cascade gain FILTER_GAIN is pre-applied to the input signal below.
    static_assert(FILTER_N_SECTIONS == N_SECTIONS,
                  "filter_taps.hpp was generated for a different N_SECTIONS - "
                  "rerun ref_generate.py");
    std::vector<std::array<T, 6>> sos(N_SECTIONS);
    for (int s = 0; s < N_SECTIONS; s++)
        for (int k = 0; k < 6; k++)
            sos[s][k] = FILTER_SOS[s][k];

    // ----- Input signal -----
    T *h_in  = (T *)malloc(N_SAMPLES * sizeof(T));  assert(h_in  != NULL);
    T *h_out = (T *)malloc(N_SAMPLES * sizeof(T));  assert(h_out != NULL);
    T *h_sol = (T *)malloc(N_SAMPLES * sizeof(T));  assert(h_sol != NULL);

    for (int i = 0; i < N_SAMPLES; i++) {
        // Float64 argument and gain, cast to float32 once - matches
        // ref_generate.py exactly (which filters this same float32 input).
        h_in[i]  = static_cast<T>(FILTER_GAIN * cos(2.0 * M_PI * INPUT_FREQ * i / INPUT_FS));
        h_sol[i] = 0;
    }

    // ----- Device setup and coefficient upload -----
    cudaSetDevice(0);
    setup_kernel_coefficients(sos);

    const int num_chunks = KERNEL_NUM_CHUNKS;
    const size_t size = N_SAMPLES * sizeof(T);

    // ----- Allocate multiple input buffers for rotation -----
    // The rotation defeats L2 cache retention across launches. Enough buffers
    // so total footprint > 3x L2. Sized against 3 MB (RTX 3060, GA106); the
    // GTX 1070 (GP104) has 2 MB, so this is conservative for both cards. For
    // large batches a single buffer already exceeds L2; we still allocate at
    // least 4 for safety.
    constexpr int L2_SIZE_BYTES = 3 * 1024 * 1024;
    const int min_buffers = 4;
    const int buffers_to_exceed_L2 = (int)((2 * L2_SIZE_BYTES + size - 1) / size);
    const int num_buffers = std::max(min_buffers, buffers_to_exceed_L2);

    std::cout << "  Input buffers = " << num_buffers
              << " (total footprint = " << (num_buffers * size / (1024.0 * 1024.0))
              << " MB)" << std::endl;

    std::vector<T*> d_in_buffers(num_buffers);
    for (int i = 0; i < num_buffers; i++) {
        assert(cudaSuccess == cudaMalloc(&d_in_buffers[i], size));
        assert(cudaSuccess == cudaMemcpy(d_in_buffers[i], h_in, size, cudaMemcpyHostToDevice));
    }

    T *d_out, *d_partcarry, *d_fullcarry;
    int *d_status;
    assert(cudaSuccess == cudaMalloc(&d_out, size));
    assert(cudaSuccess == cudaMalloc(&d_status,    num_chunks * N_SECTIONS * sizeof(int)));
    assert(cudaSuccess == cudaMalloc(&d_partcarry, num_chunks * order * N_SECTIONS * sizeof(T)));
    assert(cudaSuccess == cudaMalloc(&d_fullcarry, num_chunks * order * N_SECTIONS * sizeof(T)));
    assert(cudaSuccess == cudaMemcpy(d_out, d_in_buffers[0], size, cudaMemcpyDeviceToDevice));

    // Zero the status array ONCE (cudaMalloc does not zero memory). The
    // launch-versioned flags in ph_kernels.cuh make any further resets
    // unnecessary: flags from launch L read as "not ready" to launch L+1.
    assert(cudaSuccess == cudaMemset(d_status, 0, num_chunks * N_SECTIONS * sizeof(int)));

    // ----- Measurement loop -----
    // launch_idx increments on EVERY call — continuously across warmup and
    // the timed phase — so status flags never alias between launches. The
    // timed region is now exactly one kernel launch per iteration.
    int launch_idx = 0;
    auto launch = [&](T* d_in) {
        KERNEL_FUNC<<<KERNEL_GRID_DIM, KERNEL_TB_DIM>>>(d_in, d_out, d_status, d_partcarry, d_fullcarry, launch_idx);
        ++launch_idx;
    };

    float time_ms = measure_kernel_time(launch, d_in_buffers);

    cudaError_t err = cudaGetLastError();
    if (err != cudaSuccess) {
        printf("Kernel launch error: %s\n", cudaGetErrorString(err));
        return -1;
    }

    err = cudaDeviceSynchronize();
    if (err != cudaSuccess) {
        printf("Kernel execution error: %s\n", cudaGetErrorString(err));
        return -1;
    }

    double throughput_GSps = ((double)N_SAMPLES / (time_ms * 1e-3)) / 1e9;
    std::cout << "Execution time (P20): " << time_ms << " ms" << std::endl;
    std::cout << "Throughput:           " << throughput_GSps << " GS/s" << std::endl;

    // ----- Verify against reference.bin -----
    assert(cudaSuccess == cudaMemcpy(h_out, d_out, size, cudaMemcpyDeviceToHost));

    FILE* fp = fopen("reference.bin", "rb");
    if (fp == NULL) {
        fprintf(stderr, "ERROR: reference.bin not found. Run ref_generate.py first.\n");
        return -1;
    }
    size_t read = fread(h_sol, sizeof(float), N_SAMPLES, fp);
    fclose(fp);
    if (read != N_SAMPLES) {
        fprintf(stderr, "ERROR: reference.bin has %zu floats, expected %d\n",
                read, N_SAMPLES);
        return -1;
    }

    // Relative pass criterion: max abs error <= REL_TOL * max |reference|.
    const T REL_TOL = 1e-4f;
    T max_err = 0, max_ref = 0;
    int worst_idx = 0;
    for (int i = 0; i < N_SAMPLES; i++) {
        T diff = fabsf(h_out[i] - h_sol[i]);
        T aref = fabsf(h_sol[i]);
        if (diff > max_err) { max_err = diff; worst_idx = i; }
        if (aref > max_ref) max_ref = aref;
    }
    const T threshold = REL_TOL * max_ref;

    if (max_err <= threshold) {
        printf("Accuracy: PASSED (max abs err = %.3e, relative = %.3e, threshold = %.3e)\n",
               max_err, max_err / max_ref, threshold);
    } else {
        printf("Accuracy: FAILED — max abs err %.3e at index %d exceeds threshold %.3e "
               "(relative = %.3e, ref=%.6f, out=%.6f)\n",
               max_err, worst_idx, threshold, max_err / max_ref,
               h_sol[worst_idx], h_out[worst_idx]);
    }

    free(h_in);  free(h_out);  free(h_sol);
    for (int i = 0; i < num_buffers; i++) cudaFree(d_in_buffers[i]);
    cudaFree(d_out);
    cudaFree(d_status);  cudaFree(d_partcarry);  cudaFree(d_fullcarry);

    return (max_err <= threshold) ? 0 : 1;
}
