#!/usr/bin/env python3
"""
ref_generate.py — design the test filter, generate reference.bin, and emit
filter_taps.hpp for the CUDA drivers.

The test filter is a Butterworth lowpass of order 2*N_SECTIONS with cutoff
0.2 x Nyquist, designed directly in SOS form (scipy.signal.butter). This
replaces the old direct-form-taps + tf2sos flow: both the CUDA kernel and the
reference consume the IDENTICAL coefficients, and the designed filter is
well-conditioned (no near-unit-circle poles).

Conventions (must match the CUDA drivers, which include filter_taps.hpp):
  - Sections are normalized to b0 == 1; the removed cascade gain
    (product of the designed b0's) is pre-applied to the input signal.
  - Input signal: cos(2*pi*INPUT_FREQ*t), t = i/INPUT_FS, computed in float64,
    scaled by the (float64) gain, then cast to float32 — exactly what the
    device filters.
  - reference.bin: float64 sosfilt of that float32-cast input through the
    float32-cast normalized sections (so coefficient rounding is shared with
    the kernel), stored as float32.

Exit codes: 0 ok / 1 cross-check failed / 2 invalid arguments.
"""

import argparse
import os
import sys
import numpy as np
from scipy import signal

INPUT_FS = 1000.0     # Hz
INPUT_FREQ = 120.0    # Hz (transition band: cutoff is 0.2 * 500 = 100 Hz)
CUTOFF_WN = 0.2       # x Nyquist


def parse_args():
    p = argparse.ArgumentParser(description=__doc__.split('\n')[1])
    p.add_argument('--n-samples-log2', type=int,
                   default=int(os.environ.get('N_SAMPLES_LOG2', 0)) or None)
    p.add_argument('--n-sections', type=int,
                   default=int(os.environ.get('N_SECTIONS', 0)) or None)
    p.add_argument('--output', '-o', default='reference.bin')
    p.add_argument('--header', default='filter_taps.hpp')
    p.add_argument('--quiet', '-q', action='store_true')
    a = p.parse_args()
    if a.n_samples_log2 is None or a.n_sections is None:
        print('ERROR: N_SAMPLES_LOG2 and N_SECTIONS must be given '
              '(CLI or environment).', file=sys.stderr)
        sys.exit(2)
    if a.n_sections not in (1, 2, 4, 8):
        print(f'ERROR: unsupported N_SECTIONS={a.n_sections}', file=sys.stderr)
        sys.exit(2)
    return a


def main():
    args = parse_args()
    ns = args.n_sections
    n = 1 << args.n_samples_log2

    # ----- filter design (float64) -----
    sos = signal.butter(N=2 * ns, Wn=CUTOFF_WN, btype='lowpass', output='sos')
    gain = float(np.prod(sos[:, 0]))              # full double-precision gain
    sos_norm = sos.copy()
    for s in range(ns):
        sos_norm[s, 0:3] = sos[s, 0:3] / sos[s, 0]
    sos_f32 = sos_norm.astype(np.float32)         # what the kernel consumes

    # ----- direct-form taps for the PLR lane (same transfer function) -----
    # One merged recurrence of order 2*ns (the PLR paper's route for
    # multi-stage filters). Emitted b0-normalized so the FILTER_GAIN-scaled
    # input serves both kernel families: in exact arithmetic b0 == gain
    # (both are the product of the section gains).
    ba_b, ba_a = signal.butter(N=2 * ns, Wn=CUTOFF_WN, btype='lowpass',
                               output='ba')
    if abs(ba_b[0] - gain) > 1e-9 * abs(gain):
        print(f'ERROR: direct-form b0 ({ba_b[0]!r}) != cascade gain '
              f'({gain!r})', file=sys.stderr)
        sys.exit(1)
    plr_b = ba_b[1:] / ba_b[0]        # FIR taps past the implicit b0 == 1
    plr_a = -ba_a[1:]                 # recurrence sign: y[n] += a_j * y[n-j]

    # ----- input signal (matches the CUDA drivers exactly) -----
    i = np.arange(n, dtype=np.float64)
    x = np.cos(2.0 * np.pi * INPUT_FREQ * i / INPUT_FS)
    x_dev = (gain * x).astype(np.float32)         # device input, float32

    # ----- reference: float64 filtering of the float32 quantities -----
    ref = signal.sosfilt(sos_f32.astype(np.float64), x_dev.astype(np.float64))

    # ----- internal cross-check vs the un-normalized designed filter -----
    check = signal.sosfilt(sos, x)
    rel = np.max(np.abs(ref - check)) / max(np.max(np.abs(check)), 1e-30)
    if rel > 1e-4:
        print(f'ERROR: normalization cross-check failed (rel={rel:.3e})',
              file=sys.stderr)
        sys.exit(1)

    ref.astype(np.float32).tofile(args.output)

    # ----- emit filter_taps.hpp -----
    rows = []
    for s in range(ns):
        vals = ', '.join(f'{v:.9e}f' for v in sos_f32[s])
        rows.append(f'    {{{vals}}}')
    hdr = (
        '// Auto-generated by ref_generate.py — DO NOT EDIT.\n'
        f'// Butterworth lowpass, order {2*ns}, cutoff {CUTOFF_WN} x Nyquist.\n'
        '// Sections are normalized to b0 == 1; FILTER_GAIN is the removed\n'
        '// cascade gain and must be pre-applied to the input signal.\n'
        '#pragma once\n'
        '\n'
        f'#define FILTER_N_SECTIONS {ns}\n'
        f'static const double FILTER_GAIN = {gain!r};\n'
        f'static const double INPUT_FS    = {INPUT_FS!r};\n'
        f'static const double INPUT_FREQ  = {INPUT_FREQ!r};\n'
        '\n'
        f'static const float FILTER_SOS[{ns}][6] = {{\n'
        + ',\n'.join(rows) + '\n};\n'
        '\n'
        '// Direct-form realization of the SAME transfer function (PLR lane).\n'
        '// b0-normalized (implicit b0 == 1, gain removed = FILTER_GAIN);\n'
        '// A uses the recurrence sign convention y[n] += A[j] * y[n-j-1].\n'
        f'#define PLR_FILTER_ORDER {2*ns}\n'
        f'static const double PLR_FILTER_B[{2*ns}] = {{\n    '
        + ',\n    '.join(f'{float(v)!r}' for v in plr_b) + '\n};\n'
        f'static const double PLR_FILTER_A[{2*ns}] = {{\n    '
        + ',\n    '.join(f'{float(v)!r}' for v in plr_a) + '\n};\n'
    )
    with open(args.header, 'w') as f:
        f.write(hdr)

    if not args.quiet:
        print(f'order {2*ns}: wrote {args.output} ({n} float32 samples), '
              f'{args.header}; gain={gain:.6e}, cross-check rel={rel:.2e}, '
              f'max|ref|={np.max(np.abs(ref)):.4f}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
